[package]
name = "api_test"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version="0.5.1", features = ["json"]}
rocket_cors = "0.6"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
serde = { version = "1", features = ["derive"] }